const userName = 'Вася Пупкин';
console.log(userName[0]);
console.log(userName[1]);
console.log(userName[2]);
console.log(userName.charAt(2));
console.log(userName.length);
console.log(userName.indexOf('я'));
console.log(userName.lastIndexOf('П'));
console.log(userName.includes('П'));
console.log(userName.slice(5));
console.log(userName.slice(5, 8));